# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: careerfoundryjuan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auth-server

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30 # optional, in seconds, default is 6
  provider:
  environment:
    CLIENT_ID: ${file(./config.json):web.CLIENT_ID}
    CLIENT_SECRET: ${file(./config.json):web.CLIENT_SECRET}
    CALENDAR_ID: ${file(./config.json):web.CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/auth
          method: get

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token
          method: get

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
